[build-system]
build-backend = "hatchling.build"
requires = [
  "hatch-vcs",
  "hatchling",
]

[project]
name = "climate-literature"
description = "Measuring the size and make-up of the climate literature"
requires-python = ">=3.14"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.14",
]
dynamic = [
  "version",
]
dependencies = [
  "dvc[ssh]>=3.67.1",
  "pandas>=3.0.5",
  "pyarrow>=25.0.1",
  "snakemake>=9.26.1",
  "typer>=0.27",
]
optional-dependencies.ml = [
  "torch>=2.14",
  "transformers>=5.17",
]
optional-dependencies.nacsos = [
  "nacsos-data",
]

[tool.hatch]
version.source = "vcs"
build.targets.wheel.packages = [
  "src/climate_literature",
]

[tool.uv]
sources.nacsos-data = { git = "https://gitlab.pik-potsdam.de/mcc-apsis/nacsos/nacsos-data.git" }

[tool.ruff]
lint.select = [
  "B",
  "E",
  "F",
  "I",
  "UP",
  "W",
]

[tool.ty]
environment.python-version = "3.14"
